trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: Build
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '18.x'
      displayName: 'Install Node.js'
    - script: |
        npm install
      displayName: 'Install API dependencies'
    - script: |
        npm run build
      displayName: 'Build the API'
    - task: CopyFiles@2
      inputs:
        Contents: 'node_modules/**'
        TargetFolder: 'dist'
      displayName: 'Copy dependencies to build output directory'
    - task: CopyFiles@2
      inputs:
        Contents: 'package.json'
        TargetFolder: 'dist'
      displayName: 'Copy package.json to build output directory'
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(Build.SourcesDirectory)/dist'
        includeRootFolder: false
        archiveType: zip
        archiveFile: '$(Build.ArtifactStagingDirectory)/did-i-hike-that-api-$(Build.BuildId).zip'
      displayName: 'Create API artifact'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/did-i-hike-that-api-$(Build.BuildId).zip'
        ArtifactName: did-i-hike-that-api
      displayName: 'Publish API artifact'
